import MediaCarousel from './MediaCarousel'
import { Link } from 'react-router-dom'
import {FolderOpen,User,Robot,Medal,Stack,ArrowUpRight} from '@/components/slab'
const cards=[{to:'/projects',kind:'projects',title:'Projects',desc:'Six connected automation systems.',Icon:FolderOpen,lines:['AI Messenger Assistant','Lead Intake & BANT Scoring','Xero → Asana Reporting']},{to:'/about',kind:'about',title:'About',desc:'AI Automation Specialist.',Icon:User,lines:['Justin Automation'],photo:true},{to:'/projects',kind:'ai',title:'AI Builds',desc:'Business knowledge. Instant answers.',Icon:Robot,lines:['n8n','AI + Google Docs','Facebook Messenger']},{to:'/about',kind:'creds',title:'Credentials',desc:'Four training certificates.',Icon:Medal,lines:['CRM systems','Workflow automation']},{to:'/services',kind:'services',title:'Services',desc:'Less manual work. More room to grow.',Icon:Stack,lines:['AI Automation & Chatbots','CRM & Lead Capture','Booking & Marketing','Workflow Integrations']},{to:'/testimonials',kind:'quotes',title:'Process',desc:'A clear path from idea to launch.',Icon:ArrowUpRight,lines:['Discovery → Planning','Build → Testing','Launch → Support']}]
export default function HomeBento(){return <nav className="bento" aria-label="Explore the portfolio">{cards.map(c=>{
 const header=<header className="bento__head"><span className="bento__label"><c.Icon size={20}/><h3 className="bento__title">{c.title}</h3></span><p className="bento__desc">{c.desc}</p><ArrowUpRight className="bento__arrow" size={15}/></header>
 if(c.kind==='projects'||c.kind==='creds') return <article key={c.title} className={'bento__card bento__card--'+c.kind}>{header}<MediaCarousel kind={c.kind==='projects'?'projects':'certificates'}/></article>
 return <Link key={c.title} to={c.to} className={'bento__card bento__card--'+c.kind}>{header}<div className="bento__media jb-bento-media">{c.photo?<img src="/jbern-portrait.jpg" alt=""/>:c.lines.map(l=><span key={l}>{l}</span>)}</div></Link>
})}</nav>}
